In [1]:
import numpy as np

Создаем массив a

In [5]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Среднее значение по каждому признаку:

In [8]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2. массив a_centered

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3. 

In [10]:
a_1 = a_centered[:,0]
a_1

array([-1.,  0.,  1.,  1., -1.])

In [12]:
a_2 = a_centered[:,1]
a_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [13]:
a_centered_sp = np.dot(a_1, a_2)

a_centered_sp

8.0

In [14]:
N = a.shape[0]
N

5

In [15]:
b = a_centered_sp/(N-1)
b

2.0